### ISSUE TITLE
Convert TryChooser service to an React SPA

### ISSUE THREAD

**Issue by garbas** [mozilla/release-services#122]
Initially TryChooser code was only copied to from [build-tools](https://github.com/mozilla/build-tools/commit/cc9e80196f7c67abaa9acf3a3e434f6554fd0977) repository and included in `releng-frontend` project (look at `src/releng_frontend/src/trychooser` folder in this repository).

You can see current version of trychooser here: https://mozilla-releng.net/trychooser

# Todo

1. [ ] Create a header React component with style like here -> https://mozilla-releng.net/
2. [ ] Replace "RELEASE EGINEERING" in the header with a logo that is being discussed here -> https://github.com/mozilla/OpenDesign/issues/136. Logo should be `[moz://a] [RelEng]` or `[moz://a][Release Engineering]`.
3. [ ] Extract the data from html and - for now - hardcode them in one place somewhere in code. By data I mean `Built Types`, `Platforms`, `Unit Test Suittes`, etc.. which you can see in current version of trychooser.
4. [ ] Create a view that will display all the checkboxes in similar way as now, but using bootstrap.
5. [ ] Make sure that the form can be used on mobile
6. [ ] Check that integration with treeherder still works

**Comment by mutterroland** [comment]
I would like to learn Elm . Is this Issue still available?

**Comment by garbas** [comment]
Hi @mutterroland,

This issue is quite old and it was decided that we will not use Elm anymore ( :sob: ). We are going to use React for this. Would you be willing to write/learn some Javascript instead?

**Comment by mutterroland** [comment]
Hey @garbas ,
I would love to learn some Javascript :). It's worth mentioning that I haven't previously coded with Javascript but I would like to start doing so.  I'm up for it if you still think that's suitable for me :).

**Comment by cdikibo** [comment]
Hi @garbas ! I'm new from Outreachy looking to work with @marco-c this summer. I know React, I could possible get a Single Page App going if you give me a bit more information and agree on a mockup.

**Comment by garbas** [comment]
@mutterroland During this week we will open many more React ticket, which might be more suitable for a beginner. 
@cdikibo I will update the description of the PR with more details.

**Comment by garbas** [comment]
@cdikibo I updated the description and create a "todo" list for you. let me know if you have more questions. I see Trychooser to be a simple application where once does not need much. There is no routing, we might even skip using redux all together.

As for the building process I would keep everything simple and not bother at all with webpack etc... at all. and just include needed libraries from inside the `index.html`. I would follow something along this blog post -> https://shinglyu.github.io/web/2018/02/08/minimal-react-js-without-a-build-step-updated.html

**Comment by garbas** [comment]
@cdikibo was above description enough to get you started? or should I elaborate more.

**Comment by cdikibo** [comment]
Hi @garbas <https://github.com/garbas>

The file tree structure was off. I'm still a bit confused about the current
setup and how I should go about replace it with my files for a PR. Getting
Docker to cooperate on 4GB was a barrier on my side. Or should I just write
it in code bin and share it there.



Also, it didn't help that I was snapped up by a company last week and
signed with them. My employer values open source work so I could still work
on this by myself or could help guide @mutterroland in completing this
issue.

**Comment by garbas** [comment]
@cdikibo congrats on the new job :) code bin would be the way to go with this task since we can skip all of the docker stuff. also it would be easier to share and collaborate. if you are still interested in working on this.
