### ISSUE TITLE
Per project configuration

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#1220]
Discussed during the mid year All hands 2018: 

We'll use TOML files (parser easily available in Nix + python)

The process imply to merge various files in a specific order

1. Global config (hardcoded)
2. Home folder (optional ~/.pleaserc, essentially for credentials)
3. Root (or base folder) with config.toml
4. Per project (found from above "src" key)
5. Remote secured source, optional and depending on previous config (think of offline dev)
5.a Taskcluster
5.b Sops
5.c local GPG files

Each project can have config.nix (complex & complete) `XOR` config.toml (static simple file)

Please commands are simplified, by using fewer args:
* `--chanel=staging|production|whatever`, default to master (aka dev)
* `--config.key=value` (with key=whatever)
* `--config-file=path`

We can then deploy through: `./please deploy shipit-static-analysis --channel=staging`

All code should reside in cli_common to be accessible from both please_cli & business projects

## TODO

- [ ] remove nix/default.nix, #1363
- [ ] implement pleaserc.toml configuration without changing any functionality, #1364
- [ ] move project resolution to python, #1365 
- [ ] Takcluster hooks should be implemented in please_cli, #1374

**Comment by garbas** [comment]
I was wondering if this is possible to do in "stages" where we would gradually upgrade. I would like to avoid having to do a big rewrite, but rather include smaller changes as we go

Here are smaller tasks we could start working on:

1. remove `nix/default.nix` 

currently we use `nix/default.nix` as a single point of collecting all our projects in one place. this limits us to implementing everything in nix and in python, which is pain in the ass.

in more details, currently `./please shell` command internally calls `nix-shell nix/default.nix -A <project>`. we need to move to a more *per project* solution where we would call `nix-shell src/<project>/default.nix`. We still need to figure out how our  `default.nix` api will look like (currently we require one argument `releng_pkgs`, but this will probably change.

2. implement `pleaserc.toml` configuration without changing any functionality.

Currently our configuration is stored in `lib/please_cli/please_cli/config.py`, and idea i would like to explore is to use [context_settings](http://click.pocoo.org/6/commands/#context-defaults) when creating main please command. where `default_map` is being created by reading `pleasetc.toml` file. 

I'd love to hear if there is any other pattern with `click` library that we could explore.

3. Once 1. and 2. are done move project resolution (as it currently works, check 2 levels of folders in `src/` and look for `default.nix`) to please command.

I think above 3 tasks would be a good ground work before we move configuration around.

**Comment by garbas** [comment]
@La0 i forgot to ping you in the comment above. what do you think.

**Comment by garbas** [comment]
Also once 1. and 2. would be done we can start looking into #1221 in parallel

**Comment by La0** [comment]
A project would only be valid if it has a `default.nix` at its root, right ?
So the lookup for projects could be an N-depth find for these files, instead of `glob(*)` + `glob(*/*)`: this should ease externalizing projects.

@garbas How does the project's `default.nix` would find the root `nix/lib/default.nix` though ? It will need to hardcode the library position ? Can't we rely on a real Nix library (or derivation) for that ?

Your plan looks good, shall we create several issues and make this a meta ticket ?
