### ISSUE TITLE
shipit_static_analysis: Enable clang-format feedback in production

### ISSUE THREAD

**Issue by jankeromnes** [mozilla/release-services#1271]
Our reviewers sometimes spend a lot of time reporting coding style issues on a patch. This is perceived as one of the less valuable uses of a reviewer's time, and it could potentially be automated with a tool like `clang-format`, in order to spare Human reviewer time for more valuable things like design feedback and knowledge sharing.

TODO:
- [x] re-enable the `clang-format` analyzer on staging ~~(as well as the `before/after` mechanism as a drive-by, see #1236)~~
- [x] validate that coding style feedback on staging looks good and valuable
  - [x] fix any confusing comments or strange issues like #1121
  - [ ] limit the number of comments to a manageable count (e.g. on MozReview we don't report more than 30 comments)
  - [ ] if needed, maybe start small on a sub-directory like `/media` and expand coverage gradually
- [x] once we're sufficiently confident that `clang-format` reviews look valuable on staging, enable them in production
- [x] re-validate coding style review feedback in production, to make sure everything works well

**Comment by jankeromnes** [comment]
Note: We might want to use `./mach clang-format` as a base for the before/after analysis: https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style/Formatting_C++_Code_With_clang-format

**Comment by sylvestre** [comment]
I just had the same discussions during our respective 1:1 :)

Actually, after second thought, the nested statements might not be happening that often. And this is a small counter argument (from me, sorry :). Maybe we try and see how often we see that?

**Comment by jankeromnes** [comment]
Using `./mach clang-format` removes the dependency on `before/after`. Let's de-couple these two features, and ship each feature whenever it's ready.

**Comment by La0** [comment]
We miss 3 things before running clang-format on testing:

- [ ] Use `./mach clang-format` instead of `clang-format` directly, #1600 
- [ ] Provide patch directly from analyzer instead of rebuilding from diffs
- [ ] Filter issues by analyzer in PhabricatorReporter (aka shadow mode)

When we have these, we can run clang-format analysis like this:

* on testing with production analysis, but no reporting
* on staging with dev analysis, and reporting
* on production with production analysis, but no reporting (yet)

**Comment by La0** [comment]
Clang-format patches are published since a few months
