### ISSUE TITLE
renaming projects to 

### ISSUE THREAD

**Issue by garbas** [mozilla/release-services#1294]
Depends on #1219.

Once above ticket is implemented we can start looking of grouping projects in folders (eg, projectA/frontend, projectA/backend, ...).

- [x] `releng_docs` -> `docs`, #1532
- [x] `releng_treestatus` -> `treestatus/api`, #1533
- [ ] `releng_frontend`-> split into `treestatus/frontend`, `tokens/frontend`, `tooltool/frontend` and `notification/frontend`
- [x] `releng_tokens` -> `tokens/api`, #1534
- [x] `releng_tooltool` -> `tooltool/api`, #1536
- [x] `releng_mapper` -> `mapper/api`, #1537
- [x] `releng_notification_policy` -> `notification/policy`
- [x] `releng_notification_identity` -> `notification/identity`
- [x] `shipit_workflow` -> `shipit/api`, #1373
- [x] `shipit_frontend` -> `shipit/frontend`, #1372
- [x] `shipit_bot_uplift` -> `uplift/bot`, #1395
- [x] `shipit_uplift` -> `uplift/backend`, #1393
- [x] `shipit_frontend` (extract the uplift code) -> `uplift/frontend`, #1400
- [x] `shipit_code_coverage` -> `codecoverage/uploader`, #1448
- [x] `shipit_code_coverage_backend` -> `codecoverage/backend`, #1448
- [x] `shipit_code_coverage_crawler` -> `codecoverage/crawler`, #1448
- [x] `shipit_pulse_listener` -> `pulselistener`, #1541 
- [x] `shipit_static_analysis` -> `staticanalysis/bot`, #1402

**Comment by garbas** [comment]
i started with suggestion how to rename projects to have something we can start debating about. I'm expecting names to changed as we move with the discussion.

Guides i followed:
- shorter names, easier/faster to type
- it is ok to drop team specific (eg. "releng_") prefixes
- use grouping in folders


I hope this starts a discussion about renaming. Once we know how to rename projects. we can look how to get this done to not disrupt our development too much.

**Comment by garbas** [comment]
Looking to get feedback from everybody, what do you think?

/cc @La0 @jankeromnes @marco-c @sylvestre @rail @lundjordan

**Comment by marco-c** [comment]
Looks OK to me, maybe using _ as space is better than completely removing the spaces (e.g. code_coverage instead of codecoverage or static_analysis instead of staticanalysis).

**Comment by jankeromnes** [comment]
I agree that `code_coverage` may be a little more readable than `codecoverage`, but typing `_` is tedious so personally I still prefer `codecoverage` (not a strong opinion though).

Additionally, we could indeed rename `staticanalysis/bot` to `codereview/bot` (or just `reviewbot`).

Similarly, maybe `codecoverage` or `code_coverage` could be renamed just `coverage`?

**Comment by marco-c** [comment]
I think `reviewbot` or `codereview` might be a little too generic, as there could be other tools we implement that are not related to static analysis, but the static analysis project is only about static analysis (and linting).

**Comment by lundjordan** [comment]
Thanks for pushing through on this.

No concerns on first pass personally. The result (proj per folder) is the big win. If there is naming pattern or individual change that's requested after what has already been mentioned, I hope that it is not much to adjust at at a later point

**Comment by La0** [comment]
I'll rename the `shipit-static-analysis` to `staticanalysis` after the release. We can (and surely will) rename later if we add different code analyzers, but it's in the far future

**Comment by marco-c** [comment]
One thing I'm not fond of is that we have different terminology in config.py, in PROJECT_NAME in config.py and in setup.py and in the name of the directories.
E.g. sometimes we use staticanalysis, sometimes static-analysis, and sometimes static_analysis.
Why are we doing this? Could we always use static_analysis instead?

**Comment by marco-c** [comment]
The code coverage projects have been renamed. The only shipit_* left is shipit_pulse_listener.
