### ISSUE TITLE
Reduce static-analysis bot failures

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#1380]
I created a small script that uses Taskcluster indexed data to list all the tasks in error state (same data used by the dashboard).
For each task i download the Taskcluster raw log, and parse it for an exception message. I then categorize the errors in category.

Here are the results for the last 7 days of execution:

```
    Total phabricator = 507
    Erroneous phabricator = 143
    Counter({'merge_conflict': 132, 'mach': 10, 'empty': 1})
     
    Total mozreview = 307
    Erroneous mozreview = 124
    Counter({'mercurial_pull': 78, 'mach': 41, 'unknown': 3, 'unicode': 2}) 
```

So 1 on 3 task is failing for different reasons. We can do the following to improve the situation:

 - [ ] Fix `mach` issues #1375
 - [x] Fix `mercurial` issues #1376
 - [x] Investigate a solution for `merge_conflict` #1214 and #1215
 - [x] Categorize and report the errors #1378
 - [x] Display error stats on the dashboard #1379

**Comment by La0** [comment]
Won't fix any mozreview issues as [it's sunsetting](https://mail.mozilla.org/pipermail/firefox-dev/2018-July/006693.html).

**Comment by La0** [comment]
We are now at 85% appliance rate, much better.

**Comment by marco-c** [comment]
> What about publishing a message when it cannot be applied?

I've filed https://github.com/mozilla/release-services/issues/1542.
