### ISSUE TITLE
Rationalize usage of taskcluster scopes/roles/groups/clients

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1630]
## Motivation

Right now the scopes situation is pretty confusing.

Some of us have scopes that others don't have, some scopes are assigned both to group to which we belong and to ourselves directly, and so on.

It should be possible to add/remove contributors as we see it fit without involving taskcluster team.

## TODO:

- [x] create contributors and developers
  - https://mozillians.org/en-US/group/release-services-developers/
  - https://mozillians.org/en-US/group/release-services-contributors/
- [ ] rename `releng-svc*` worker types to `release*`worker types
- [ ] secrets should be places under `project/release/` namespace
  secrets should follow the following naming
  `project/release/<channel>/<project>/<version>`
  where channel is production, staging, testing, master or contributors

- [ ] create roles
    - contributors (`project:release:group/contributors`) and `mozillians-group:release-services-contributors` should assume this role. the following scopes should be assigned:

  ```
  secrets:get:project/release/contributors
  TODO...
  ```

    - developers (project:release:group/developers) and `mozillians-group:release-services-contributors` should assume this role. the following scopes should be assigned:

  ```
  secrets:get:project/release/developers
  TODO...
  ```

    - admins (project:release:group/admins) and this role is assigned individually to developers. the following scopes should be assigned:

  ```
  assume:hook-id:project-release/*
  assume:project:release:*
  auth:create-client:project/release/*
  auth:create-role:hook-id:project-release/*
  auth:create-role:project:release:*
  auth:delete-client:project/release/*
  auth:delete-role:hook-id:project-release/*
  auth:delete-role:project:release:*
  auth:disable-client:project/release/*
  auth:enable-client:project/release/*
  auth:reset-access-token:project/release/*
  auth:update-client:project/release/*
  auth:update-role:hook-id:project-release/*
  auth:update-role:project:release:*
  aws-provisioner:manage-worker-type:release*
  hooks:modify-hook:project-release/*
  hooks:trigger-hook:project-release/*
  index:insert-task:project.release.*
  project:release:*
  secrets:get:project/release/*
  secrets:set:project/release/*
  ```

   for project specific roles we should follow a naming scheme: `project:release:project/<project>/<custom-role-name>`

**Comment by garbas** [comment]
I added it as discussion item for next meeting
