### ISSUE TITLE
[meta] Static analysis performance issues

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#1922]
This is a meta bug to track the issues related to degraded performance in static analysis, like #1754 and other similar reports where SA issues are intermittent.

Basically we currently have too many failed tasks (~ 25%) which do not report at all on Phabricator revisions, mainly due to faulty mercurial clones.

Actions to do:

- [x] Remove Taskcluster cache #1923 
- [x] Better logs for mercurial clone #1924
- [x] Watchdog around mercurial clone (if removing the cache is not enough to make the clone reliable) #1925 
- [ ] Detect task failures in pulselistener & restart tasks #704, #1127 & #1926 
- [x] Get failed status when tasks get killed by Taskcluster #1927 
- [x] Export & display diff ID #1921

**Comment by La0** [comment]
Release 56 was deployed yesterday, static analysis bot is OK with these performance enhancements.
The "killed for timeout" status in the frontend allows me to track bad tasks, and confirm our suspicions: some mercurial are extremely long (in the update phase). These are rare occurences.

Here are [two](https://tools.taskcluster.net/groups/K4z2Fq4ZQwGs9DeolY5YgA/tasks/K4z2Fq4ZQwGs9DeolY5YgA/runs/0/logs/public%2Flogs%2Flive.log) [examples](https://tools.taskcluster.net/groups/cRao7MwlRxCwMY89JOLLpA/tasks/cRao7MwlRxCwMY89JOLLpA/runs/0/logs/public%2Flogs%2Flive.log) of a clone taking close to 2 hours.

I'm making a PR for #1925 to add a watchdog around the mercurial clone, so that pulselistener can restart them after implementing #1926 

Ping @marco-c so i don't forget

**Comment by La0** [comment]
I'm closing this since the move to try should have helped a lot (no more watchdog issues!)

**Comment by sylvestre** [comment]
Bravo for the hard work!

Le ven. 10 mai 2019 à 17:40, Bastien Abadie <notifications@github.com> a
écrit :
