### ISSUE TITLE
Code review bot cleanup

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#2087]
- [ ] Remove local analyzers, deps and deprecated code (#2071)
- [ ] Need to merge RemoteWorkflow in Workflow, and put the resulting class in a single file (#2081)
- [ ] Need to merge PhabricatorRevision in Revision (#1899)
- [ ] Need to remove Coverity options/secret and only keep the full stack option (#2082)
- [ ] Coverity has a lot less unit tests, as they were only around the local analyzer (#2079 and #2080)
- [ ] Simplify `CoverityIssue.__init__` as only one of two format is now supported (#2083)
- [ ] https://github.com/mozilla/release-services/pull/2071#discussion_r282490997
- [ ] Move clang checks validation in `./mach static-analysis check` [Bug 1550516](https://bugzilla.mozilla.org/show_bug.cgi?id=1550516) 
- [ ] Add 3rd party checks on mozlint & static-analysis check [Bug 1550516](https://bugzilla.mozilla.org/show_bug.cgi?id=1550517)
