### ISSUE TITLE
Switch all python projects python 3.6

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#867]
All python projects:
- [x] backend-common (`lib/backend-common`), used as a dependency by releng-tokens
- [x] cli-common (`lib/cli-common`), used as a dependency by releng-tokens
- [x] please-cli (`lib/please-cli`), #1278
- [x] releng-docs (`src/releng_docs`), #1278
- [x] releng-mapper (`src/releng_mapper`),  #1367
- [x] releng-notification-identity (`src/releng_notification_identity`), #1312
- [x] releng-notification-policy (`src/releng_notification_policy`), #1312
- [x] releng-tokens (`src/releng_tokens`), started with python 3.6
- [x] releng-tooltool (`src/releng_tooltool`),  #1366
- [x] releng-treestatus (`src/releng_treestatus`), #1368
- [x] shipit-bot-uplift (`src/shipit_bot_uplift`), #1283
- [x] shipit-code-coverage (`src/shipit_code_coverage`), #1280
- [x] shipit-code-coverage_backend (`src/shipit_code_coverage_backend`), already using 3.6
- [x] shipit-pulse-listener (`src/shipit_pulse_listener`), #1281
- [x] shipit-static-analysis (`src/shipit_static_analysis`), #1282
- [x] shipit-uplift (`src/shipit_uplift`), already using 3.6
- [x] shipit-workflow (`src/shipit_workflow`), #1293

**Comment by garbas** [comment]
i'd say lets update nixpkgs and pypi2nix first and then switch to python 3.6 and see what breaks. probably best to do it right after we do a release

**Comment by garbas** [comment]
I think @La0 proposed this some time ago, but we said we would wait a bit more not to be the first one to adopt python 3.6 :)

**Comment by rail** [comment]
> @rail should we update shipit_workflow to python 3.6 already?

I think so. At least I don't know any blockers.

**Comment by garbas** [comment]
i'm assigning this to myself since there are only projects i own left to do.
