### ISSUE TITLE
switch to nix 2.0

### ISSUE THREAD

**Issue by garbas** [mozilla/release-services#902]
# TODO

- [ ] update `nix/setup.sh` to install 2.0 version, this script should be also used to setup base docker image
- [ ] `nix-push` is deprecated use `nix copy`
- [ ] run `nix-shell` with `--pure` argument except when running `./please shell`

**Comment by garbas** [comment]
this was done some time ago in #928
