### ISSUE TITLE
Improve static analysis and code coverage resilience

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#954]
- [x] Use a separate Taskcluster provisioner #946  
- [x] Only publish new issues to be idempotent
- [x] Make code coverage idempotent #1118
- [x] Enhance pulse listener monitoring to restart tasks in exception state #704
- [ ] Enhance pulse listener to keep tasks in the queue until they are finished #1127

**Comment by marco-c** [comment]
I filed #704 about the second a while ago (but I was thinking of retrying both exception and failed tasks).
Retrying failed tasks could be a problem for tasks that are not idempotent.

**Comment by garbas** [comment]
I think 2 things need to be done:
 - make static analysis tasks idempotent. so even if we trigger a task 2 times it wouldn't be a problem.
 - add some persistence logic to pulse listener which would track what was analyzed already. because of idempotency we don't have to worry about race conditions. in the worse case some tasks will be ran 2 times.

**Comment by garbas** [comment]
with above 2 things even when taskcluster misbehaves we would still be able to handle the queue after some time.

**Comment by La0** [comment]
Static analysis needs to detect if an issue has already been filled to be idempotent.
Right now you can re-run a task, but it will post the same issues.

**Comment by La0** [comment]
@garbas Pulse listener already has some persistence logic for monitoring purposes. We also already track the status updates of tasks, so triggering an action for failed/exception tasks is easy.
But we don't have *true* persistence using a database, so if you restart the pulse listener Heroku worker, you'll lose previous data.

We could use an Heroku database, like for `shipit-uplift` but that seems overkill.

**Comment by marco-c** [comment]
The task could check if an issue for a given patch has already been posted, it wouldn't be perfect as there could be race conditions, but it would almost always work.

**Comment by sylvestre** [comment]
I like the last idea. I prefer to have rare duplicate contents than missing one.

**Comment by La0** [comment]
Ok, i'll start the implementation in a PR. It should be possible for mozreview, no idea for phabricator :disappointed:

**Comment by marco-c** [comment]
To do `Enhance pulse listener monitoring to restart tasks in exception state`, we need to make shipit code coverage idempotent too. It should be easy (just check if a report has already been uploaded to codecov/coveralls and don't upload it again if it was already uploaded).

**Comment by marco-c** [comment]
The code coverage task is now idempotent, so only #704 is left.

**Comment by La0** [comment]
With the move to try, we have > 90% succesful runs for now, should be at 100% in a few days
